### ISSUE TITLE
PArrayIndexOutOfBoundsException missing

### ISSUE THREAD

**Issue by Phasip** [utwente-fmt/spins#5]
The latest git version does not compile and complains about not finding
spins.promela.compiler.ltsmin.util.PArrayIndexOutOfBoundsException

Seems like this file was not added during commit 5ca3df95829e2652da2d0c8d262d796c37432e0f ( https://github.com/utwente-fmt/spins/commit/5ca3df95829e2652da2d0c8d262d796c37432e0f )

**Comment by alaarman** [comment]
Fixed in the next branch. Thanks.
