### ISSUE TITLE
proctype with arguments

### ISSUE THREAD

**Issue by wolvre** [utwente-fmt/spins#8]
Hi,

How would spins handle a proctype with arguments, e.g.

proctype a_proc(byte i)

That is, instead of having multiple copies of a_proc in a program, one may need to instantiate a_proc with specific input values (for i).

Best,

**Comment by alaarman** [comment]
Hello wolvre,

spins does some static analysis to bind a copy of a proc to a run statement.
If this fails it returns an error message.

**Comment by alaarman** [comment]
reopen if this didn't help
